export const CONTACT_GET_SUCCESS = 'CONTACT_GET_SUCCESS'
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS'
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE'
export const UPDATE_CONTACT_MESSAGE = 'UPDATE_CONTACT_MESSAGE'
export const MESSAGE_SEND_SUCCESS_CLEAR = 'MESSAGE_SEND_SUCCESS_CLEAR'
export const SEEN_MESSAGE = 'SEEN_MESSAGE'
export const DELIVERED_MESSAGE = 'DELIVERED_MESSAGE'
export const UPDATE = 'UPDATE'
export const MESSAGE_GET_SUCCESS_CLEAR = 'MESSAGE_GET_SUCCESS_CLEAR'
export const SEEN_ALL = 'SEEN_ALL'


