export const OFFER_GET_SUCCESS = 'OFFER_GET_SUCCESS'
export const OFFER_SEND_SUCCESS = 'OFFER_SEND_SUCCESS'
export const SOCKET_OFFER = 'SOCKET_OFFER'
export const UPDATE_CONTACT_OFFER = 'UPDATE_CONTACT_OFFER'
export const UPDATE_OFFER = 'UPDATE_OFFER'
export const OFFER_GET_SUCCESS_CLEAR = 'OFFER_GET_SUCCESS_CLEAR'
export const DELIVERED_OFFER = 'DELIVERED_OFFER'

